#!/bin/python

import math
import os
import random
import re
import sys

# Complete the luckBalance function below.
def luckBalance(k, contests):
    ar1 = []
    add1 = 0
    add2 = 0
    c=0
    for i in range(len(contests)):
        if(contests[i][1]==1):
            ar1.append(contests[i][0])
        if(contests[i][1]==0):
            add2 = add2+contests[i][0]
    ar1.sort()
    ar1.reverse()

    for j in range(len(ar1)):
        if(c+1<=k):
            c=c+1
            add1 = add1+ar1[j]
        else:
            add1 = add1-ar1[j]
    
    return add2+add1
           

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = raw_input().split()

    n = int(nk[0])

    k = int(nk[1])

    contests = []

    for _ in xrange(n):
        contests.append(map(int, raw_input().rstrip().split()))

    result = luckBalance(k, contests)

    fptr.write(str(result) + '\n')

    fptr.close()
