#!/bin/python

import math
import os
import random
import re
import sys

# Complete the checkMagazine function below.
def checkMagazine(magazine, note):
    st = dict()
    for j in magazine:
        st[j]=st.setdefault(j,0)+1
    for i in note:
        if i in st:
            st[i]=st[i]-1
            if(st[i]<0):
                print "No"
                return 
        else:
            print "No"
            return
    print "Yes"
    return


if __name__ == '__main__':
    mn = raw_input().split()

    m = int(mn[0])

    n = int(mn[1])

    magazine = raw_input().rstrip().split()

    note = raw_input().rstrip().split()

    checkMagazine(magazine, note)
